// spring-security-modules/spring-security-oauth2-bff/react-ui/app/login-error/page.tsx
"use client";

import Link from "next/link";

export default function LoginError() {
  const uri = window.location.search;
  const params = uri ? new URLSearchParams(uri.substring(1)) : new URLSearchParams();

  return (
    <main className="min-h-screen">
      <div className="flex">
        <span className="ml-2"></span>
        <button>
          <Link href="/">Home</Link>
        </button>
        <span className="m-auto"></span>
        <h1>Login error</h1>
        <span className="m-auto"></span>
      </div>
      <div className="flex flex-col items-center justify-between p-24">
        <p>{params.get('error')}</p>
      </div>
    </main>
  );
}

// spring-security-modules/spring-security-oauth2-bff/vue-ui/src/views/LoginError.vue
<script setup lang="ts">
function message() {
  const searchStr = window.location.search
  const params = searchStr ? new URLSearchParams(searchStr.substring(1)) : new URLSearchParams();
  return params.get('error');
}
</script>

<template>
  <main>
    <h1></h1>
    <p>{{ message() }}</p>
  </main>
</template>
